name: base
dependencies:
- nvidia::cudatoolkit=11.3.1
- numpy=1.21.2
- pillow=8.4.0
- pytorch::pytorch=1.10.0=py3.9_cuda11.3_cudnn8.2.0_0
- scipy=1.7.1
- pytorch::torchvision=0.11.1=py39_cu113
- tqdm=4.62.3
- scikit-learn=1.0.2
- matplotlib
- ipython=8.3.0
- pandas=1.4.2
- nltk=3.7